package net.suncaper.springboot.mapper;

import java.util.List;
import net.suncaper.springboot.domain.Sku;
import net.suncaper.springboot.domain.SkuExample;
import org.apache.ibatis.annotations.Param;

public interface SkuMapper extends UserMapperExt {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    long countByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    int deleteByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    int insert(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    int insertSelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    List<Sku> selectByExample(SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    static Sku selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    int updateByExample(@Param("record") Sku record, @Param("example") SkuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    int updateByPrimaryKeySelective(Sku record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    int updateByPrimaryKey(Sku record);
}