package net.suncaper.springboot.domain;

import java.math.BigDecimal;

public class Sku {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.id
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.product_id
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sku_code
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private String skuCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.price
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.low_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private Integer lowStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.amount
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.color
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.color_id
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private Long colorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.pic
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.sale
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private Integer sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.promotion_price
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private BigDecimal promotionPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pms_sku_stock.lock_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    private Integer lockStock;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.id
     *
     * @return the value of pms_sku_stock.id
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.id
     *
     * @param id the value for pms_sku_stock.id
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.product_id
     *
     * @return the value of pms_sku_stock.product_id
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.product_id
     *
     * @param productId the value for pms_sku_stock.product_id
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sku_code
     *
     * @return the value of pms_sku_stock.sku_code
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public String getSkuCode() {
        return skuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sku_code
     *
     * @param skuCode the value for pms_sku_stock.sku_code
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setSkuCode(String skuCode) {
        this.skuCode = skuCode == null ? null : skuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.price
     *
     * @return the value of pms_sku_stock.price
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.price
     *
     * @param price the value for pms_sku_stock.price
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.stock
     *
     * @return the value of pms_sku_stock.stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.stock
     *
     * @param stock the value for pms_sku_stock.stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.low_stock
     *
     * @return the value of pms_sku_stock.low_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public Integer getLowStock() {
        return lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.low_stock
     *
     * @param lowStock the value for pms_sku_stock.low_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setLowStock(Integer lowStock) {
        this.lowStock = lowStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.amount
     *
     * @return the value of pms_sku_stock.amount
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.amount
     *
     * @param amount the value for pms_sku_stock.amount
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.color
     *
     * @return the value of pms_sku_stock.color
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.color
     *
     * @param color the value for pms_sku_stock.color
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setColor(Sku color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.color_id
     *
     * @return the value of pms_sku_stock.color_id
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public Long getColorId() {
        return colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.color_id
     *
     * @param colorId the value for pms_sku_stock.color_id
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setColorId(Long colorId) {
        this.colorId = colorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.pic
     *
     * @return the value of pms_sku_stock.pic
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.pic
     *
     * @param pic the value for pms_sku_stock.pic
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.sale
     *
     * @return the value of pms_sku_stock.sale
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public Integer getSale() {
        return sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.sale
     *
     * @param sale the value for pms_sku_stock.sale
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setSale(Integer sale) {
        this.sale = sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.promotion_price
     *
     * @return the value of pms_sku_stock.promotion_price
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public BigDecimal getPromotionPrice() {
        return promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.promotion_price
     *
     * @param promotionPrice the value for pms_sku_stock.promotion_price
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setPromotionPrice(BigDecimal promotionPrice) {
        this.promotionPrice = promotionPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pms_sku_stock.lock_stock
     *
     * @return the value of pms_sku_stock.lock_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public Integer getLockStock() {
        return lockStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pms_sku_stock.lock_stock
     *
     * @param lockStock the value for pms_sku_stock.lock_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    public void setLockStock(Integer lockStock) {
        this.lockStock = lockStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Sku other = (Sku) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProductId() == null ? other.getProductId() == null : this.getProductId().equals(other.getProductId()))
            && (this.getSkuCode() == null ? other.getSkuCode() == null : this.getSkuCode().equals(other.getSkuCode()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getStock() == null ? other.getStock() == null : this.getStock().equals(other.getStock()))
            && (this.getLowStock() == null ? other.getLowStock() == null : this.getLowStock().equals(other.getLowStock()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getColor() == null ? other.getColor() == null : this.getColor().equals(other.getColor()))
            && (this.getColorId() == null ? other.getColorId() == null : this.getColorId().equals(other.getColorId()))
            && (this.getPic() == null ? other.getPic() == null : this.getPic().equals(other.getPic()))
            && (this.getSale() == null ? other.getSale() == null : this.getSale().equals(other.getSale()))
            && (this.getPromotionPrice() == null ? other.getPromotionPrice() == null : this.getPromotionPrice().equals(other.getPromotionPrice()))
            && (this.getLockStock() == null ? other.getLockStock() == null : this.getLockStock().equals(other.getLockStock()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_sku_stock
     *
     * @mbg.generated Mon Jul 29 11:44:08 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProductId() == null) ? 0 : getProductId().hashCode());
        result = prime * result + ((getSkuCode() == null) ? 0 : getSkuCode().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getStock() == null) ? 0 : getStock().hashCode());
        result = prime * result + ((getLowStock() == null) ? 0 : getLowStock().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getColor() == null) ? 0 : getColor().hashCode());
        result = prime * result + ((getColorId() == null) ? 0 : getColorId().hashCode());
        result = prime * result + ((getPic() == null) ? 0 : getPic().hashCode());
        result = prime * result + ((getSale() == null) ? 0 : getSale().hashCode());
        result = prime * result + ((getPromotionPrice() == null) ? 0 : getPromotionPrice().hashCode());
        result = prime * result + ((getLockStock() == null) ? 0 : getLockStock().hashCode());
        return result;
    }
}