package net.suncaper.springboot.mapper;

import java.util.List;
import net.suncaper.springboot.domain.Commerce;
import net.suncaper.springboot.domain.CommerceExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface CommerceMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    long countByExample(CommerceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    int deleteByExample(CommerceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    int insert(Commerce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    int insertSelective(Commerce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    List<Commerce> selectByExample(CommerceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    Commerce selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Commerce record, @Param("example") CommerceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    int updateByExample(@Param("record") Commerce record, @Param("example") CommerceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    int updateByPrimaryKeySelective(Commerce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    int updateByPrimaryKey(Commerce record);
}