package net.suncaper.springboot.mapper;

import java.util.List;

import net.suncaper.springboot.domain.Product;
import net.suncaper.springboot.domain.Shoppingcart;
import net.suncaper.springboot.domain.ShoppingcartExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface ShoppingcartMapper extends ShoppingcartMapperExt{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    long countByExample(ShoppingcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    int deleteByExample(ShoppingcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    int insert(Shoppingcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    int insertSelective(Shoppingcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    List<Shoppingcart> selectByExample(ShoppingcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    Shoppingcart selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Shoppingcart record, @Param("example") ShoppingcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Shoppingcart record, @Param("example") ShoppingcartExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Shoppingcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Shoppingcart record);
}