server:
  port: 8280

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hk?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver