server:
  port: 8180

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hk?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

 redis:
  host: 127.0.0.1
  port: 6379
  password:
  database: 0
  lettuce:
    pool:
      max-active: 32
      max-wait: 300ms
      max-idle: 16
      min-idle: 8

