package net.suncaper.springboot.domain;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.province
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.county
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    private String county;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.town
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    private String town;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.t_u_name
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    private String tUName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.phone
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.detail
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    private String detail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.t_u_id
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    private String tUId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.province
     *
     * @return the value of address.province
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.province
     *
     * @param province the value for address.province
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city
     *
     * @return the value of address.city
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city
     *
     * @param city the value for address.city
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.county
     *
     * @return the value of address.county
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.county
     *
     * @param county the value for address.county
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.town
     *
     * @return the value of address.town
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.town
     *
     * @param town the value for address.town
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.t_u_name
     *
     * @return the value of address.t_u_name
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public String gettUName() {
        return tUName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.t_u_name
     *
     * @param tUName the value for address.t_u_name
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public void settUName(String tUName) {
        this.tUName = tUName == null ? null : tUName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.phone
     *
     * @return the value of address.phone
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.phone
     *
     * @param phone the value for address.phone
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.detail
     *
     * @return the value of address.detail
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.detail
     *
     * @param detail the value for address.detail
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.t_u_id
     *
     * @return the value of address.t_u_id
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public String gettUId() {
        return tUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.t_u_id
     *
     * @param tUId the value for address.t_u_id
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    public void settUId(String tUId) {
        this.tUId = tUId == null ? null : tUId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Address other = (Address) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProvince() == null ? other.getProvince() == null : this.getProvince().equals(other.getProvince()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getCounty() == null ? other.getCounty() == null : this.getCounty().equals(other.getCounty()))
            && (this.getTown() == null ? other.getTown() == null : this.getTown().equals(other.getTown()))
            && (this.gettUName() == null ? other.gettUName() == null : this.gettUName().equals(other.gettUName()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getDetail() == null ? other.getDetail() == null : this.getDetail().equals(other.getDetail()))
            && (this.gettUId() == null ? other.gettUId() == null : this.gettUId().equals(other.gettUId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table address
     *
     * @mbg.generated Mon Aug 05 17:10:06 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProvince() == null) ? 0 : getProvince().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getCounty() == null) ? 0 : getCounty().hashCode());
        result = prime * result + ((getTown() == null) ? 0 : getTown().hashCode());
        result = prime * result + ((gettUName() == null) ? 0 : gettUName().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getDetail() == null) ? 0 : getDetail().hashCode());
        result = prime * result + ((gettUId() == null) ? 0 : gettUId().hashCode());
        return result;
    }
}