package net.suncaper.springboot.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class CommerceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public CommerceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTOIdIsNull() {
            addCriterion("t_o_id is null");
            return (Criteria) this;
        }

        public Criteria andTOIdIsNotNull() {
            addCriterion("t_o_id is not null");
            return (Criteria) this;
        }

        public Criteria andTOIdEqualTo(String value) {
            addCriterion("t_o_id =", value, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdNotEqualTo(String value) {
            addCriterion("t_o_id <>", value, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdGreaterThan(String value) {
            addCriterion("t_o_id >", value, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdGreaterThanOrEqualTo(String value) {
            addCriterion("t_o_id >=", value, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdLessThan(String value) {
            addCriterion("t_o_id <", value, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdLessThanOrEqualTo(String value) {
            addCriterion("t_o_id <=", value, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdLike(String value) {
            addCriterion("t_o_id like", value, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdNotLike(String value) {
            addCriterion("t_o_id not like", value, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdIn(List<String> values) {
            addCriterion("t_o_id in", values, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdNotIn(List<String> values) {
            addCriterion("t_o_id not in", values, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdBetween(String value1, String value2) {
            addCriterion("t_o_id between", value1, value2, "tOId");
            return (Criteria) this;
        }

        public Criteria andTOIdNotBetween(String value1, String value2) {
            addCriterion("t_o_id not between", value1, value2, "tOId");
            return (Criteria) this;
        }

        public Criteria andProIdIsNull() {
            addCriterion("pro_id is null");
            return (Criteria) this;
        }

        public Criteria andProIdIsNotNull() {
            addCriterion("pro_id is not null");
            return (Criteria) this;
        }

        public Criteria andProIdEqualTo(String value) {
            addCriterion("pro_id =", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotEqualTo(String value) {
            addCriterion("pro_id <>", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdGreaterThan(String value) {
            addCriterion("pro_id >", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdGreaterThanOrEqualTo(String value) {
            addCriterion("pro_id >=", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdLessThan(String value) {
            addCriterion("pro_id <", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdLessThanOrEqualTo(String value) {
            addCriterion("pro_id <=", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdLike(String value) {
            addCriterion("pro_id like", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotLike(String value) {
            addCriterion("pro_id not like", value, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdIn(List<String> values) {
            addCriterion("pro_id in", values, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotIn(List<String> values) {
            addCriterion("pro_id not in", values, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdBetween(String value1, String value2) {
            addCriterion("pro_id between", value1, value2, "proId");
            return (Criteria) this;
        }

        public Criteria andProIdNotBetween(String value1, String value2) {
            addCriterion("pro_id not between", value1, value2, "proId");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Integer value) {
            addCriterion("quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Integer value) {
            addCriterion("quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Integer value) {
            addCriterion("quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Integer value) {
            addCriterion("quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Integer value) {
            addCriterion("quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Integer value) {
            addCriterion("quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Integer> values) {
            addCriterion("quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Integer> values) {
            addCriterion("quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Integer value1, Integer value2) {
            addCriterion("quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Integer value1, Integer value2) {
            addCriterion("quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andPrepriceIsNull() {
            addCriterion("preprice is null");
            return (Criteria) this;
        }

        public Criteria andPrepriceIsNotNull() {
            addCriterion("preprice is not null");
            return (Criteria) this;
        }

        public Criteria andPrepriceEqualTo(BigDecimal value) {
            addCriterion("preprice =", value, "preprice");
            return (Criteria) this;
        }

        public Criteria andPrepriceNotEqualTo(BigDecimal value) {
            addCriterion("preprice <>", value, "preprice");
            return (Criteria) this;
        }

        public Criteria andPrepriceGreaterThan(BigDecimal value) {
            addCriterion("preprice >", value, "preprice");
            return (Criteria) this;
        }

        public Criteria andPrepriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("preprice >=", value, "preprice");
            return (Criteria) this;
        }

        public Criteria andPrepriceLessThan(BigDecimal value) {
            addCriterion("preprice <", value, "preprice");
            return (Criteria) this;
        }

        public Criteria andPrepriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("preprice <=", value, "preprice");
            return (Criteria) this;
        }

        public Criteria andPrepriceIn(List<BigDecimal> values) {
            addCriterion("preprice in", values, "preprice");
            return (Criteria) this;
        }

        public Criteria andPrepriceNotIn(List<BigDecimal> values) {
            addCriterion("preprice not in", values, "preprice");
            return (Criteria) this;
        }

        public Criteria andPrepriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("preprice between", value1, value2, "preprice");
            return (Criteria) this;
        }

        public Criteria andPrepriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("preprice not between", value1, value2, "preprice");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commerce_item
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 06 20:39:20 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}