package net.suncaper.springboot.domain;

import java.math.BigDecimal;

public class Commerce {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commerce_item.id
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commerce_item.t_o_id
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    private String tOId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commerce_item.pro_id
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    private String proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commerce_item.quantity
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    private Integer quantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column commerce_item.preprice
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    private BigDecimal preprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commerce_item.id
     *
     * @return the value of commerce_item.id
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commerce_item.id
     *
     * @param id the value for commerce_item.id
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commerce_item.t_o_id
     *
     * @return the value of commerce_item.t_o_id
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public String gettOId() {
        return tOId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commerce_item.t_o_id
     *
     * @param tOId the value for commerce_item.t_o_id
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public void settOId(String tOId) {
        this.tOId = tOId == null ? null : tOId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commerce_item.pro_id
     *
     * @return the value of commerce_item.pro_id
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commerce_item.pro_id
     *
     * @param proId the value for commerce_item.pro_id
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commerce_item.quantity
     *
     * @return the value of commerce_item.quantity
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commerce_item.quantity
     *
     * @param quantity the value for commerce_item.quantity
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column commerce_item.preprice
     *
     * @return the value of commerce_item.preprice
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public BigDecimal getPreprice() {
        return preprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column commerce_item.preprice
     *
     * @param preprice the value for commerce_item.preprice
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    public void setPreprice(BigDecimal preprice) {
        this.preprice = preprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Commerce other = (Commerce) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.gettOId() == null ? other.gettOId() == null : this.gettOId().equals(other.gettOId()))
            && (this.getProId() == null ? other.getProId() == null : this.getProId().equals(other.getProId()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()))
            && (this.getPreprice() == null ? other.getPreprice() == null : this.getPreprice().equals(other.getPreprice()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commerce_item
     *
     * @mbg.generated Tue Aug 06 20:39:20 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((gettOId() == null) ? 0 : gettOId().hashCode());
        result = prime * result + ((getProId() == null) ? 0 : getProId().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        result = prime * result + ((getPreprice() == null) ? 0 : getPreprice().hashCode());
        return result;
    }
}