package net.suncaper.springboot.domain;

import java.math.BigDecimal;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.pay_id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private String payId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.shi_id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private String shiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.t_u_id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private String tUId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.order_status
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.total_price
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private BigDecimal totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.discount
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private BigDecimal discount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.t_u_name
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private String tUName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.phone
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.address
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.pay_id
     *
     * @return the value of t_order.pay_id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public String getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.pay_id
     *
     * @param payId the value for t_order.pay_id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void setPayId(String payId) {
        this.payId = payId == null ? null : payId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.shi_id
     *
     * @return the value of t_order.shi_id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public String getShiId() {
        return shiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.shi_id
     *
     * @param shiId the value for t_order.shi_id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void setShiId(String shiId) {
        this.shiId = shiId == null ? null : shiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.t_u_id
     *
     * @return the value of t_order.t_u_id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public String gettUId() {
        return tUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.t_u_id
     *
     * @param tUId the value for t_order.t_u_id
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void settUId(String tUId) {
        this.tUId = tUId == null ? null : tUId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.order_status
     *
     * @return the value of t_order.order_status
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.order_status
     *
     * @param orderStatus the value for t_order.order_status
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.total_price
     *
     * @return the value of t_order.total_price
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public BigDecimal getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.total_price
     *
     * @param totalPrice the value for t_order.total_price
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void setTotalPrice(BigDecimal totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.discount
     *
     * @return the value of t_order.discount
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public BigDecimal getDiscount() {
        return discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.discount
     *
     * @param discount the value for t_order.discount
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void setDiscount(BigDecimal discount) {
        this.discount = discount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.t_u_name
     *
     * @return the value of t_order.t_u_name
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public String gettUName() {
        return tUName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.t_u_name
     *
     * @param tUName the value for t_order.t_u_name
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void settUName(String tUName) {
        this.tUName = tUName == null ? null : tUName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.phone
     *
     * @return the value of t_order.phone
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.phone
     *
     * @param phone the value for t_order.phone
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.address
     *
     * @return the value of t_order.address
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.address
     *
     * @param address the value for t_order.address
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Order other = (Order) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getPayId() == null ? other.getPayId() == null : this.getPayId().equals(other.getPayId()))
            && (this.getShiId() == null ? other.getShiId() == null : this.getShiId().equals(other.getShiId()))
            && (this.gettUId() == null ? other.gettUId() == null : this.gettUId().equals(other.gettUId()))
            && (this.getOrderStatus() == null ? other.getOrderStatus() == null : this.getOrderStatus().equals(other.getOrderStatus()))
            && (this.getTotalPrice() == null ? other.getTotalPrice() == null : this.getTotalPrice().equals(other.getTotalPrice()))
            && (this.getDiscount() == null ? other.getDiscount() == null : this.getDiscount().equals(other.getDiscount()))
            && (this.gettUName() == null ? other.gettUName() == null : this.gettUName().equals(other.gettUName()))
            && (this.getPhone() == null ? other.getPhone() == null : this.getPhone().equals(other.getPhone()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbg.generated Wed Aug 07 10:16:52 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getPayId() == null) ? 0 : getPayId().hashCode());
        result = prime * result + ((getShiId() == null) ? 0 : getShiId().hashCode());
        result = prime * result + ((gettUId() == null) ? 0 : gettUId().hashCode());
        result = prime * result + ((getOrderStatus() == null) ? 0 : getOrderStatus().hashCode());
        result = prime * result + ((getTotalPrice() == null) ? 0 : getTotalPrice().hashCode());
        result = prime * result + ((getDiscount() == null) ? 0 : getDiscount().hashCode());
        result = prime * result + ((gettUName() == null) ? 0 : gettUName().hashCode());
        result = prime * result + ((getPhone() == null) ? 0 : getPhone().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        return result;
    }
}