package net.suncaper.springboot.domain;

public class Shoppingcart {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.id
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.pro_id
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    private String proId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.t_u_id
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    private String tUId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shopping_cart.quantity
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.id
     *
     * @return the value of shopping_cart.id
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.id
     *
     * @param id the value for shopping_cart.id
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.pro_id
     *
     * @return the value of shopping_cart.pro_id
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.pro_id
     *
     * @param proId the value for shopping_cart.pro_id
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.t_u_id
     *
     * @return the value of shopping_cart.t_u_id
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    public String gettUId() {
        return tUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.t_u_id
     *
     * @param tUId the value for shopping_cart.t_u_id
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    public void settUId(String tUId) {
        this.tUId = tUId == null ? null : tUId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shopping_cart.quantity
     *
     * @return the value of shopping_cart.quantity
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shopping_cart.quantity
     *
     * @param quantity the value for shopping_cart.quantity
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Shoppingcart other = (Shoppingcart) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProId() == null ? other.getProId() == null : this.getProId().equals(other.getProId()))
            && (this.gettUId() == null ? other.gettUId() == null : this.gettUId().equals(other.gettUId()))
            && (this.getQuantity() == null ? other.getQuantity() == null : this.getQuantity().equals(other.getQuantity()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shopping_cart
     *
     * @mbg.generated Sat Aug 03 17:25:41 GMT+08:00 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProId() == null) ? 0 : getProId().hashCode());
        result = prime * result + ((gettUId() == null) ? 0 : gettUId().hashCode());
        result = prime * result + ((getQuantity() == null) ? 0 : getQuantity().hashCode());
        return result;
    }
}